package burp;


import yaml.YamlUtil;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;

import static burp.BurpExtender.Filter_path;

public class Config {
    private JPanel one;
    private JTextField txtfield1;
    public String yaml_path = BurpExtender.Yaml_Path;
    public JSpinner spinner1;
    private BurpExtender burp;
    public JTabbedPane ruleTabbedPane;
    public TabTitleEditListener ruleSwitch;
    protected static JPopupMenu tabMenu = new JPopupMenu();
    private JMenuItem closeTabMenuItem = new JMenuItem("Delete");
    private static int RulesInt = 0;
    public static DefaultTableModel model;

    public static String new_Rules() {
        RulesInt += 1;
        return "New " + RulesInt;
    }


    public void newTab() {
        Object[][] data = new Object[][]{{false, "New Name", "(New Regex)", "gray", "any", "nfa", false}};
        insertTab(ruleTabbedPane, Config.new_Rules(), data);
    }

    public void insertTab(JTabbedPane pane, String title, Object[][] data) {
        pane.addTab(title, new JLabel());
        pane.remove(pane.getSelectedIndex());
        pane.addTab("...", new JLabel());
    }

    public void closeTabActionPerformed(ActionEvent e) {

        if (ruleTabbedPane.getTabCount() > 2) {
            Dialog frame = new JDialog();//构造一个新的JFrame，作为新窗口。
            frame.setBounds(
                    new Rectangle(
                            // 让新窗口与SwingTest窗口示例错开50像素。
                            620,
                            300,
                            // 窗口总大小-500像素
                            200,
                            100
                    )
            );


            JPanel xin = new JPanel();
            xin.setLayout(null);

            JLabel Tips = new JLabel("Are you sure you want to delete");
            Tips.setBounds(20, 10, 200, 20);
            xin.add(Tips);

            // Ok
            JButton Ok_button = new JButton("Yes");
            Ok_button.setBounds(120, 40, 60, 20);
            xin.add(Ok_button);
            Ok_button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String type = ruleTabbedPane.getTitleAt(ruleTabbedPane.getSelectedIndex());
                    View Remove_view = burp.views.get(type);
                    if (Remove_view != null) {
                        for (View.LogEntry l : Remove_view.log) {
                            YamlUtil.removeYaml(l.id, BurpExtender.Yaml_Path);
                        }
                    }
                    ruleTabbedPane.remove(ruleTabbedPane.getSelectedIndex());
                    frame.dispose();

                }
            });

            // no
            JButton No_button = new JButton("NO");
            No_button.setBounds(30, 40, 60, 20);
            xin.add(No_button);
            No_button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    frame.dispose();

                }
            });


            ((JDialog) frame).getContentPane().add(xin);
            frame.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);    // 设置模式类型。
            frame.setVisible(true);


        }
    }

    public Config(BurpExtender burp) {
        tabMenu.add(closeTabMenuItem);
        closeTabMenuItem.addActionListener(e -> closeTabActionPerformed(e));
        this.burp = burp;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        one = new JPanel();
        one.setLayout(null);
        one.setBounds(0, 0, 1180, 500);


        // Yaml File Path 文本展示框
        JLabel yaml_Path = new JLabel("Yaml File Path:");
        yaml_Path.setBounds(5, 20, 100, 50);

        // 展示路径
        txtfield1 = new JTextField();   //创建文本框
        txtfield1.setText(yaml_path);    //设置文本框的内容
        txtfield1.setEditable(false);
        txtfield1.setBounds(110, 35, 800, 25);


        // Online Update按钮
        JButton Online_Update_button = new JButton("Update");
        Online_Update_button.setBounds(510, 5, 87, 23);
        Online_Update_Yaml(Online_Update_button);

        // load 按钮
        JButton load_button = new JButton("Load Yaml");
        load_button.setBounds(617, 5, 100, 23);
        load_button_Yaml(load_button);

        // 线程选择
        JLabel thread_num = new JLabel("Thread Numbers:");
        thread_num.setBounds(690, 55, 140, 50);
        SpinnerNumberModel model1 = new SpinnerNumberModel(10, 1, 500, 3);
        this.spinner1 = new JSpinner(model1);
        ((JSpinner.DefaultEditor) this.spinner1.getEditor()).getTextField().setEditable(false);

        this.spinner1.setBounds(810, 70, 100, 23);




        // add按钮
        JButton add_button = new JButton("Add");
        add_button.setBounds(5, 150, 70, 23);
        Add_Button_Yaml(add_button, yaml_path);

        // Edit按钮
        JButton edit_button = new JButton("Edit");
        edit_button.setBounds(5, 175, 70, 23);
//        Edit_Button_Yaml(edit_button,yaml_path,view_class,log);
        Edit_Button_Yaml(edit_button, yaml_path);

        // Del按钮
        JButton remove_button = new JButton("Del");
        remove_button.setBounds(5, 200, 70, 23);
        Del_Button_Yaml(remove_button, yaml_path);



        // 展示界面容器
        ruleTabbedPane = new JTabbedPane();
        this.ruleSwitch = new TabTitleEditListener(ruleTabbedPane, this.burp);
        ruleTabbedPane.setBounds(80, 130, 1185, 350);
        Bfunc.show_yaml(burp);
        ruleTabbedPane.addMouseListener(ruleSwitch);

        //过滤路径页面容器
        model = new DefaultTableModel();
        model.addColumn("Filter Path");
        JTable jTable = new JTable(model);
        JScrollPane jscrollPane = new JScrollPane(jTable);
        jscrollPane.setBounds(920,5,340,90);

        //加载数据
        loadData();

        //底部面板输入和按钮
        JTextField inputField = new JTextField();
        inputField.setBounds(920,97,340,23);
        //add
        JButton addButton = new JButton("Add");
        addButton.setBounds(1262,97,60,23);
        // 添加按钮点击事件监听器
        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // 获取用户输入的数据
                String content = inputField.getText();
                // 将新内容添加到表格模型中
                model.addRow(new Object[]{content});
                // 清空输入字段
                inputField.setText("");
                //保存数据
                saveData();
            }
        });

        //edit
        JButton editButton = new JButton("Edit");
        editButton.setBounds(1262,72,60,23);
        editButton.addActionListener(e -> {
            int selectedRow = jTable.getSelectedRow();
            if (selectedRow != -1) {
                String newContent = inputField.getText();
                model.setValueAt(newContent, selectedRow, 0);
                inputField.setText(""); // 清空输入字段
                saveData(); // 保存数据
            }
        });

        //delete
        JButton delButton = new JButton("Del");
        delButton.setBounds(1262,47,60,23);
        delButton.addActionListener(e -> {
            int selectRow = jTable.getSelectedRow();
            if (selectRow != -1) {
                model.removeRow(selectRow);
                saveData();
            }
        });



//        // Switch 文本展示框
//        JLabel Expansion_switch = new JLabel("Extend Switch:");
//        Expansion_switch.setBounds(5, -10, 100, 50);

        // 开启按钮
//        JButton on_off_button = new JButton("Stop");
        JButton on_off_button = new JButton("Start");
        on_off_button.setBounds(20, 5, 70, 23);
        Color Primary = on_off_button.getBackground();
//        on_off_button.setBackground(Color.green);
        on_off_Button_action(on_off_button, Primary);

//        // Switch 文本展示框
//        JLabel Carry_head = new JLabel("Carry Head:");
//        Carry_head.setBounds(224, -10, 100, 50);

        // 携带head按钮
        JButton carry_head_button = new JButton("Head_On");
        carry_head_button.setBounds(110, 5, 90, 23);
        carry_head_Button_action(carry_head_button, Primary);


        // DomainScan按钮
        JButton DomainScan_button = new JButton("DomainScan_On");
        DomainScan_button.setBounds(220, 5, 140, 23);
        DomainScan_Button_action(DomainScan_button, DomainScan_button.getBackground());



        // bypass按钮
        JButton bypass_button = new JButton("Bypass_On");
        bypass_button.setBounds(380, 5, 110, 23);
        bypass_Button_action(bypass_button, bypass_button.getBackground());

        //filter 按钮
        JButton Filter_button = new JButton("Filter_On");
        Filter_button.setBounds(737, 5, 100, 23);
        Filter_Button_action(Filter_button, Filter_button.getBackground());

        //list 文本框
        JLabel list = new JLabel("List:");
        list.setBounds(880,5,80,23);


        // Filter_Host 文本展示框
        JLabel Filter_Host = new JLabel("Filter_Host:");
        Filter_Host.setBounds(5, 70, 100, 25);

        // Host 输入框
        JTextField Host_txtfield = new JTextField();   //创建文本框
        Host_txtfield.setText("*");    //设置文本框的内容
        Host_txtfield.setBounds(110, 70, 572, 25);
        burp.Host_txtfield = Host_txtfield;


//        添加到主面板
        one.add(yaml_Path);
        one.add(txtfield1);
        one.add(Online_Update_button);
        one.add(load_button);
        one.add(DomainScan_button);
        one.add(bypass_button);
        one.add(Filter_button);
        one.add(list);
        one.add(add_button);
        one.add(edit_button);
        one.add(remove_button);
        one.add(ruleTabbedPane);
        one.add(jscrollPane);
        one.add(inputField);
        one.add(addButton);
        one.add(editButton);
        one.add(delButton);
        one.add(thread_num);
        one.add(spinner1);
//        one.add(Expansion_switch);
        one.add(on_off_button);
//        one.add(Carry_head);
        one.add(carry_head_button);
        one.add(Filter_Host);
        one.add(Host_txtfield);


    }

    private void carry_head_Button_action(JButton Button_one, Color Primary) {

        Button_one.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (burp.Carry_head) {
                    burp.Carry_head = false;
                    Button_one.setText("Head_On");
                    Button_one.setBackground(Primary);
                } else {
                    burp.Carry_head = true;
                    Button_one.setText("Head_Off");
                    Button_one.setBackground(Color.green);
                }

            }
        });
    }


    private void on_off_Button_action(JButton Button_one, Color Primary) {

        Button_one.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (burp.on_off) {
                    burp.on_off = false;
                    Button_one.setText("Start");
                    Button_one.setBackground(Primary);
                } else {
                    burp.on_off = true;
                    Button_one.setText("Stop");
                    Button_one.setBackground(Color.green);
                }

            }
        });
    }


    private void bypass_Button_action(JButton Button_one, Color Primary) {

        Button_one.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (burp.Bypass) {
                    burp.Bypass = false;
                    Button_one.setText("Bypass_On");
                    Button_one.setBackground(Primary);
                } else {
                    burp.Bypass = true;
                    Button_one.setText("Bypass_Off");
                    Button_one.setBackground(Color.green);
                }

            }
        });
    }


    private void DomainScan_Button_action(JButton Button_one, Color Primary) {

        Button_one.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (burp.DomainScan) {
                    burp.DomainScan = false;
                    Button_one.setText("DomainScan_On");
                    Button_one.setBackground(Primary);
                } else {
                    burp.DomainScan = true;
                    Button_one.setText("DomainScan_Off");
                    Button_one.setBackground(Color.green);
                }

            }
        });
    }

    private void Filter_Button_action(JButton Button_one, Color Primary) {
        Button_one.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (burp.Filter) {
                    burp.Filter = false;
                    Button_one.setText("Filter_On");
                    Button_one.setBackground(Primary);
                } else {
                    burp.Filter = true;
                    Button_one.setText("Filter_Off");
                    Button_one.setBackground(Color.green);
                }
            }
        });
    }


    private void Online_Update_Yaml(JButton Button_one) {

        Button_one.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                YamlUtil.init_Yaml(burp, one);
            }
        });
    }


     private void Edit_Button_Yaml(JButton Button_one, String yaml_path1) {
        Button_one.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JDialog frame = new JDialog();//构造一个新的JFrame，作为新窗口。
                frame.setBounds(
                        new Rectangle(
                                // 让新窗口与SwingTest窗口示例错开50像素。
                                620,
                                300,
                                // 窗口总大小-500像素
                                300,
                                300
                        )
                );
                String type = ruleTabbedPane.getTitleAt(ruleTabbedPane.getSelectedIndex());
                View view_class = burp.views.get(type);

                JPanel xin = new JPanel();
                xin.setLayout(null);
                // Name
                JLabel Name_field = new JLabel("Name :");
                JTextField Name_text = new JTextField();
                Name_text.setText(view_class.Choice.name);
                Name_field.setBounds(10, 5, 40, 20);
                Name_text.setBounds(65, 5, 200, 20);
                xin.add(Name_field);
                xin.add(Name_text);

                // Method
                JLabel Method_field = new JLabel("Method :");
//                JTextField Method_text = new JTextField();
                JComboBox Method_text = new JComboBox();    //创建JComboBox
                Method_text.addItem("GET");    //向下拉列表中添加一项
                Method_text.addItem("POST");    //向下拉列表中添加一项
                Method_text.setSelectedItem(view_class.Choice.method);
                Method_field.setBounds(10, 45, 40, 20);
                Method_text.setBounds(65, 45, 200, 20);
                xin.add(Method_field);
                xin.add(Method_text);

                // Url
                JLabel Url_field = new JLabel("Url :");
                JTextField Url_text = new JTextField();
                Url_text.setText(view_class.Choice.url);
                Url_field.setBounds(10, 85, 40, 20);
                Url_text.setBounds(65, 85, 200, 20);
                xin.add(Url_field);
                xin.add(Url_text);

                // Re
                JLabel Re_field = new JLabel("Re :");
                JTextField Re_text = new JTextField();
                Re_text.setText(view_class.Choice.re);
                Re_field.setBounds(10, 125, 40, 20);
                Re_text.setBounds(65, 125, 200, 20);
                xin.add(Re_field);
                xin.add(Re_text);

                // Info
                JLabel Info_field = new JLabel("Info :");
                JTextField Info_text = new JTextField();
                Info_text.setText(view_class.Choice.info);
                Info_field.setBounds(10, 165, 40, 20);
                Info_text.setBounds(65, 165, 200, 20);
                xin.add(Info_field);
                xin.add(Info_text);

                // state
                JLabel State_field = new JLabel("state :");
                JTextField State_text = new JTextField();
                State_text.setText(view_class.Choice.state);
                State_field.setBounds(10, 205, 40, 20);
                State_text.setBounds(65, 205, 200, 20);
                xin.add(State_field);
                xin.add(State_text);

                // Ok
                JButton Ok_button = new JButton("OK");
                Ok_button.setBounds(200, 245, 60, 20);
                xin.add(Ok_button);
                Ok_button.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        String name = Name_text.getText();
                        String url = Url_text.getText();
                        String method = (String) Method_text.getSelectedItem();
                        String re = Re_text.getText();
                        String info = Info_text.getText();
                        String state = State_text.getText();
                        Map<String, Object> add_map = new HashMap<String, Object>();
                        add_map.put("id", Integer.parseInt(view_class.Choice.id));
                        add_map.put("type", type);
                        add_map.put("loaded", view_class.Choice.loaded);
                        add_map.put("name", name);
                        add_map.put("method", method);
                        add_map.put("url", url);
                        add_map.put("re", re);
                        add_map.put("info", info);
                        add_map.put("state", state);
                        YamlUtil.updateYaml(add_map, yaml_path1);
//                        burp.views = Bfunc.Get_Views();
//                        Bfunc.show_yaml(burp);
                        Bfunc.show_yaml_view(burp, view_class, type);
                        frame.dispose();

                    }
                });

                // no
                JButton No_button = new JButton("NO");
                No_button.setBounds(130, 245, 60, 20);
                xin.add(No_button);
                No_button.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        frame.dispose();

                    }
                });


                frame.getContentPane().add(xin);
                frame.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);    // 设置模式类型。
                frame.setVisible(true);

            }
        });

    }


    private void Del_Button_Yaml(JButton Button_one, String yaml_path1) {

        Button_one.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String type = ruleTabbedPane.getTitleAt(ruleTabbedPane.getSelectedIndex());
                View view_class = burp.views.get(type);
                if (view_class.Choice != null) {
                    JDialog frame = new JDialog();//构造一个新的JFrame，作为新窗口。
                    frame.setBounds(
                            new Rectangle(
                                    // 让新窗口与SwingTest窗口示例错开50像素。
                                    620,
                                    300,
                                    // 窗口总大小-500像素
                                    200,
                                    100
                            )
                    );


                    JPanel xin = new JPanel();
                    xin.setLayout(null);

                    JLabel Tips = new JLabel("Are you sure you want to delete");
                    Tips.setBounds(20, 10, 200, 20);
                    xin.add(Tips);

                    // Ok
                    JButton Ok_button = new JButton("Yes");
                    Ok_button.setBounds(120, 40, 60, 20);
                    xin.add(Ok_button);
                    Ok_button.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            YamlUtil.removeYaml(view_class.Choice.id, yaml_path1);
//                            burp.views = Bfunc.Get_Views();
                            Bfunc.show_yaml_view(burp, view_class, type);
                            frame.dispose();

                        }
                    });

                    // no
                    JButton No_button = new JButton("NO");
                    No_button.setBounds(30, 40, 60, 20);
                    xin.add(No_button);
                    No_button.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            frame.dispose();

                        }
                    });


                    frame.getContentPane().add(xin);
                    frame.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);    // 设置模式类型。
                    frame.setVisible(true);

                }

            }
        });
    }


    private void Add_Button_Yaml(JButton Button_one, String yaml_path1) {

        Button_one.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
//                burp.call.printOutput(ruleSwitch.ruleEditTextField.getText().trim());
                JDialog frame = new JDialog();//构造一个新的JFrame，作为新窗口。
                frame.setBounds(
                        new Rectangle(
                                // 让新窗口与SwingTest窗口示例错开50像素。
                                620,
                                300,
                                // 窗口总大小-500像素
                                300,
                                300
                        )
                );
                String type = ruleTabbedPane.getTitleAt(ruleTabbedPane.getSelectedIndex());
                JPanel xin = new JPanel();
                xin.setLayout(null);
                // Name
                JLabel Name_field = new JLabel("Name :");
                JTextField Name_text = new JTextField();
                Name_field.setBounds(10, 5, 40, 20);
                Name_text.setBounds(65, 5, 200, 20);
                xin.add(Name_field);
                xin.add(Name_text);

                // Method
                JLabel Method_field = new JLabel("Method :");
                JComboBox Method_text = new JComboBox();    //创建JComboBox
                Method_text.addItem("GET");    //向下拉列表中添加一项
                Method_text.addItem("POST");    //向下拉列表中添加一项
                Method_field.setBounds(10, 45, 40, 20);
                Method_text.setBounds(65, 45, 200, 20);
                xin.add(Method_field);
                xin.add(Method_text);

                // Url
                JLabel Url_field = new JLabel("Url :");
                JTextField Url_text = new JTextField();
                Url_field.setBounds(10, 85, 40, 20);
                Url_text.setBounds(65, 85, 200, 20);
                xin.add(Url_field);
                xin.add(Url_text);

                // Re
                JLabel Re_field = new JLabel("Re :");
                JTextField Re_text = new JTextField();
                Re_field.setBounds(10, 125, 40, 20);
                Re_text.setBounds(65, 125, 200, 20);
                xin.add(Re_field);
                xin.add(Re_text);

                // Info
                JLabel Info_field = new JLabel("Info :");
                JTextField Info_text = new JTextField();
                Info_field.setBounds(10, 165, 40, 20);
                Info_text.setBounds(65, 165, 200, 20);
                xin.add(Info_field);
                xin.add(Info_text);

                // State
                JLabel State_field = new JLabel("State :");
                JTextField State_text = new JTextField();
                State_field.setBounds(10, 205, 40, 20);
                State_text.setBounds(65, 205, 200, 20);
                xin.add(State_field);
                xin.add(State_text);


                // Ok
                JButton Ok_button = new JButton("OK");
                Ok_button.setBounds(200, 245, 60, 20);
                xin.add(Ok_button);
                Ok_button.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        int id = 0;
                        Map<String, Object> Yaml_Map = YamlUtil.readYaml(yaml_path1);
                        List<Map<String, Object>> List1 = (List<Map<String, Object>>) Yaml_Map.get("Load_List");
                        for (Map<String, Object> zidian : List1) {
                            if ((int) zidian.get("id") > id) {
                                id = (int) zidian.get("id");
                            }
                        }
                        id += 1;
                        String name = Name_text.getText();
                        String url = Url_text.getText();
                        String method = (String) Method_text.getSelectedItem();
                        String re = Re_text.getText();
                        String info = Info_text.getText();
                        String state = State_text.getText();
                        Map<String, Object> add_map = new HashMap<String, Object>();
                        add_map.put("type", type);
                        add_map.put("id", id);
                        add_map.put("loaded", true);
                        add_map.put("name", name);
                        add_map.put("method", method);
                        add_map.put("url", url);
                        add_map.put("re", re);
                        add_map.put("info", info);
                        add_map.put("state", state);
                        YamlUtil.addYaml(add_map, yaml_path1);
                        Bfunc.show_yaml_view(burp, burp.views.get(type), type);
                        frame.dispose();

                    }
                });

                // no
                JButton No_button = new JButton("NO");
                No_button.setBounds(130, 245, 60, 20);
                xin.add(No_button);
                No_button.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        frame.dispose();

                    }
                });


                frame.getContentPane().add(xin);
                frame.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);    // 设置模式类型。
                frame.setVisible(true);

            }
        });
    }


    private void load_button_Yaml(JButton Button_one) {
        Button_one.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Bfunc.show_yaml(burp);
            }
        });


    }

    // 从文件加载数据
    private static void loadData() {
        File file = new File(Filter_path);
        if (file.exists()) {
            try (Scanner scanner = new Scanner(file)) {
                while (scanner.hasNextLine()) {
                    String line = scanner.nextLine();
                    model.addRow(new Object[]{line});
                }
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
        }
    }

    // 保存数据到文件
    private static void saveData() {
        try (PrintWriter writer = new PrintWriter(new FileWriter(Filter_path))) {
            int rowCount = model.getRowCount();
            for (int i = 0; i < rowCount; i++) {
                String content = (String) model.getValueAt(i, 0);
                writer.println(content);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }


    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        $$$setupUI$$$();
        return one;
    }

}

